trigger:
- master

pool:
  vmImage: 'ubuntu-20.04'

variables:
  GOBIN:  '$(GOPATH)/bin' # Go binaries path
  GOROOT: '/usr/local/go1.15' # Go installation path
  GOPATH: '$(system.defaultWorkingDirectory)/gopath' # Go workspace path
  modulePath: '$(GOPATH)/src/github.com/$(build.repository.name)' # Path to the module's code

steps:
- script: |
    echo 'CLIENT_PATH=test_path' > .env
    go build .
  workingDirectory: '$(modulePath)'
  displayName: 'Get dependencies, then build'
