trigger:
- master

resources:
- repo: self

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: GoTool@0
  inputs:
    version: '1.15.3'

- script: |
    echo 'CLIENT_PATH=test_path' > .env
    make start
    curl -d '{"msg":"testing123123"}' -H 'Content-Type: application/json' http://localhost:8080/api/test
    make stop
  workingDirectory: '$(System.DefaultWorkingDirectory)'
  displayName: 'Build and test'
